/**
 * @file gpio.h
 * @brief TEST-ONLY stub. Real projects get this file auto-generated by
 * STM32CubeMX (board pin/port macros like LEFT_DRIVE_ENA_GPIO_Port).
 * It's included unconditionally from CAL_GPIO.h, so a stub must exist
 * for the PC-side test build to compile even though no test in this
 * project currently needs a real pin macro from it.
 */
#ifndef GPIO_H
#define GPIO_H

#include "stm32g0xx_hal.h"

/* controller.c la static PMDC struct initializers ku thevaiyaana
 * board pin/port macros. Real project la idha STM32CubeMX
 * auto-generate pannum (Core/Inc/gpio.h). Namba test ku, real
 * hardware address theva illa -- fake non-NULL pointers podharom,
 * so PMDC.c logic (mocked ah irukkum) evlo "port/pin" arguments
 * kondu correctly call aaguthunu verify pannalaam.
 */
#define LEFT_DRIVE_ENA_GPIO_Port   ((GPIO_TypeDef *)0x50000000)
#define LEFT_DRIVE_ENA_Pin         ((uint16_t)0x0001)

#define RIGHT_DRIVE_ENA_GPIO_Port  ((GPIO_TypeDef *)0x50000400)
#define RIGHT_DRIVE_ENA_Pin        ((uint16_t)0x0002)

#define BRUSH_ENA_GPIO_Port        ((GPIO_TypeDef *)0x50000800)
#define BRUSH_ENA_Pin              ((uint16_t)0x0004)

#define PUMP_ENA_GPIO_Port         ((GPIO_TypeDef *)0x50000C00)
#define PUMP_ENA_Pin               ((uint16_t)0x0008)

#endif /* GPIO_H */
