/**
 * @file hal_stubs.h
 * @brief TEST-ONLY support code. NOT part of the real firmware build.
 *
 * controller.c references three real STM32 peripheral handles directly
 * (`huart1`, `htim1`, `htim3`) via `extern` declarations reached through
 * CAL_UART.h / CAL_PWM.h. In the real firmware these are defined in
 * main.c (generated by STM32CubeMX). For the PC-side test build we
 * provide storage for them here instead -- without touching any of your
 * source files.
 *
 * It also provides a controlled way to escape controller.c's
 * `for(;;)` main loop during a test: HAL_Delay(50) is called once at
 * the end of every loop iteration, so we intercept that call and, after
 * a chosen number of iterations, longjmp back out to the test.
 */
#ifndef HAL_STUBS_H
#define HAL_STUBS_H

#include <setjmp.h>
#include "stm32g0xx_hal.h"

extern UART_HandleTypeDef huart1;
extern TIM_HandleTypeDef  htim1;
extern TIM_HandleTypeDef  htim3;

/* setjmp(hal_stub_loop_escape) here in the test, then call
 * initializeAndRunController() -- once HAL_Delay() has been called
 * `iterations` times, we longjmp back to that setjmp point. */
extern jmp_buf hal_stub_loop_escape;

/* Arm the escape hatch. Call this before invoking
 * initializeAndRunController() in a test. Pass -1 to disable
 * (HAL_Delay becomes a harmless no-op). */
void hal_stub_arm_loop_escape(int iterations);

#endif /* HAL_STUBS_H */
