/**
  @file hal_stubs.h
  @brief Test-only support code. NOT part of the real firmware build.
 
  controller.c directly references three STM32 peripheral handles
  (`huart1`, `htim1`, and `htim3`) through `extern` declarations
  provided by CAL_UART.h and CAL_PWM.h.
 
  In the actual firmware, these handles are defined in main.c,
  which is generated by STM32CubeMX. For the PC-based test build,
  we provide substitute storage for them here without modifying
  any of the production source files.
 
  This file also provides a controlled mechanism for exiting the
  `for(;;)` main loop in controller.c during testing. Since
  `HAL_Delay(50)` is called once at the end of each loop iteration,
  we intercept that call and, after a specified number of iterations,
  use `longjmp()` to return control back to the test.
 */

#ifndef HAL_STUBS_H
#define HAL_STUBS_H

#include <setjmp.h>
#include "stm32g0xx_hal.h"

extern UART_HandleTypeDef huart1;
extern TIM_HandleTypeDef  htim1;
extern TIM_HandleTypeDef  htim3;

/* Call setjmp(hal_stub_loop_escape) in the test, and then invoke
initializeAndRunController(). Once HAL_Delay() has been called
the specified number of `iterations`, we use longjmp() to return execution to the original setjmp() point.
 */

extern jmp_buf hal_stub_loop_escape;

/* Enable the escape hatch before calling
  initializeAndRunController() in a test.
 
  Pass -1 to disable the mechanism, causing HAL_Delay() to behave
  as a harmless no-op without triggering a longjmp().
 */

void hal_stub_arm_loop_escape(int iterations);

#endif /* HAL_STUBS_H */
