/**
 * @file gpio.h
 * @brief Test-only stub. In a real project, this file is automatically
 * generated by STM32CubeMX and contains board-specific pin and port
 * macros (for example, LEFT_DRIVE_ENA_GPIO_Port).
 *
 * Since CAL_GPIO.h includes this file unconditionally, a stub version
 * must be provided to allow the PC-side test build to compile, even
 * though none of the current tests require any actual pin macros from it.
 */

#ifndef GPIO_H
#define GPIO_H

#include "stm32g0xx_hal.h"

/* Board-specific pin and port macros required by the static PMDC
 * structure initializers in controller.c.
 *
 * In the real project, these are automatically generated by
 * STM32CubeMX (Core/Inc/gpio.h).
 *
 * For unit testing, actual hardware addresses are not required, so
 * we use fake non-NULL pointers instead. This allows us to verify
 * that the PMDC logic (with hardware dependencies mocked) invokes
 * the correct functions with the expected port and pin arguments.
 */

#define LEFT_DRIVE_ENA_GPIO_Port   ((GPIO_TypeDef *)0x50000000)
#define LEFT_DRIVE_ENA_Pin         ((uint16_t)0x0001)

#define RIGHT_DRIVE_ENA_GPIO_Port  ((GPIO_TypeDef *)0x50000400)
#define RIGHT_DRIVE_ENA_Pin        ((uint16_t)0x0002)

#define BRUSH_ENA_GPIO_Port        ((GPIO_TypeDef *)0x50000800)
#define BRUSH_ENA_Pin              ((uint16_t)0x0004)

#define PUMP_ENA_GPIO_Port         ((GPIO_TypeDef *)0x50000C00)
#define PUMP_ENA_Pin               ((uint16_t)0x0008)

#endif /* GPIO_H */
