/*
	For PMDC.c, I used CMock to mock the real hardware abstraction layers, CAL_GPIO and CAL_PWM, following exactly the same pattern used for mocking adc.c in PPT-4.
PMDC.c includes the real headers, CAL_GPIO.h and CAL_PWM.h (through PMDC.h → CAL.h). However, this test file includes the CMock-generated headers, mock_CAL_GPIO.h and mock_CAL_PWM.h.
During the build, the Ceedling build system links mock_CAL_GPIO.c and mock_CAL_PWM.c instead of the real CAL_GPIO.c and CAL_PWM.c. As a result, the tests can isolate and verify only the PMDC logic without interacting with actual hardware.

 */

#include "unity.h"
#include "PMDC.h"
#include "mock_CAL_GPIO.h"
#include "mock_CAL_PWM.h"

/* CAL.h unconditionally includes CAL_UART.h and CAL_timer.h, even though PMDC.c never calls any of their functions.
We mock these dependencies here to prevent Ceedling from pulling in the real CAL_UART.c and CAL_timer.c implementations, which depend on actual STM32 HAL functions that are not available in the PC-based test environment.*/

#include "mock_CAL_UART.h"
#include "mock_CAL_timer.h"

/*IMPORTANT: These must be real, addressable objects, not arbitrary integer-cast pointers such as (TIM_HandleTypeDef*)0x1000.
The mocks generated by CMock perform a byte-for-byte memory comparison on pointer arguments to support deep matching of structures and arrays. As a result, the framework may actually dereference both the expected and actual pointers at runtime.
Using an arbitrary fake address could therefore cause a crash. In contrast, a real static object—even if it is otherwise unused—always resides in valid memory and is safe to access.*/

static TIM_HandleTypeDef fake_timer_storage;
static GPIO_TypeDef       fake_en_port_storage;
static TIM_HandleTypeDef *fake_timer    = &fake_timer_storage;
static GPIO_TypeDef      *fake_en_port  = &fake_en_port_storage;

static PMDC motor;

void setUp(void)
{
    motor.mode      = PWM_mode;
    motor.Ftimer    = fake_timer;
    motor.Fchannel  = 1;
    motor.Rtimer    = fake_timer;
    motor.Rchannel  = 2;
    motor.Fwd_Port  = NULL;
    motor.Fwd_Pin   = 0;
    motor.Rev_Port  = NULL;
    motor.Rev_Pin   = 0;
    motor.EN_Port   = fake_en_port;
    motor.EN_Pin    = 5;
    motor.dutyCycle = 0;
    motor.currentRPM = 0;
    motor.maxRPM    = 6000;
}

void tearDown(void) {}

/*  PMDC_init  */

void test_PMDC_init_starts_both_PWM_channels(void)
{
    /* When PMDC_init() is configured in PWM mode, it should invoke 
 CAL_PWM_Start() for both the Forward and Reverse channels, following the order defined in PMDC.c.
 */
   
    CAL_PWM_Start_ExpectAndReturn(fake_timer, 1, CAL_OK);
    CAL_PWM_Start_ExpectAndReturn(fake_timer, 2, CAL_OK);

    bool result = PMDC_init(&motor);

    TEST_ASSERT_TRUE(result);
    TEST_ASSERT_EQUAL_UINT8(0, motor.dutyCycle);
    TEST_ASSERT_EQUAL_INT16(0, motor.currentRPM);
}

void test_PMDC_init_NULL_pointer_returns_false(void)
{

	/* No CAL_* functions should be invoked when a NULL pointer is provided. */

    bool result = PMDC_init(NULL);
    TEST_ASSERT_FALSE(result);
}

/*  PMDC_setDutyCycle -- Forward direction (positive duty cycle)   */

void test_PMDC_setDutyCycle_positive_enables_motor_and_drives_forward(void)
{
    /* Expected call order (PMDC_PWM_rotateForward padi):
     *   1. CAL_GPIO_Write(EN_Port, EN_Pin, SET)   -- motor enable
     *   2. CAL_PWM_SetDutyCycle(Rtimer, Rchannel, 0)   -- reverse = 0
     *   3. CAL_PWM_SetDutyCycle(Ftimer, Fchannel, 60)  -- forward = duty
     */
    CAL_GPIO_Write_ExpectAndReturn(fake_en_port, 5, SET, CAL_OK);
    CAL_PWM_SetDutyCycle_ExpectAndReturn(fake_timer, 2, 0, CAL_OK);
    CAL_PWM_SetDutyCycle_ExpectAndReturn(fake_timer, 1, 60, CAL_OK);

    bool result = PMDC_setDutyCycle(&motor, 60);

    TEST_ASSERT_TRUE(result);
    TEST_ASSERT_EQUAL_UINT8(60, motor.dutyCycle);

    /* NOTE -- likely bug in PMDC.c, intentionally left unchanged:
 currentRPM = (int16_t)(dutyCycle * maxRPM) / 100
 Due to C operator precedence, the cast is applied BEFORE the
 division. As a result, dutyCycle * maxRPM (60 * 6000 = 360000)
 overflows the int16_t range before being divided by 100, rather
 than producing the presumably intended result:

  (int16_t)((dutyCycle * maxRPM) / 100) = 3600
  The wrapped value asserted by this test (323) reflects the actual behavior of the current implementation.
  This is a good candidate for a source-code fix. Let me know if you'd like it to be corrected.
 */
    
    TEST_ASSERT_EQUAL_INT16(323, motor.currentRPM);
}

/* ------------------------------------------------------------------ */
/* PMDC_setDutyCycle -- Reverse direction (negative duty cycle)       */
/* ------------------------------------------------------------------ */

void test_PMDC_setDutyCycle_negative_enables_motor_and_drives_reverse(void)
{
    CAL_GPIO_Write_ExpectAndReturn(fake_en_port, 5, SET, CAL_OK);
    CAL_PWM_SetDutyCycle_ExpectAndReturn(fake_timer, 1, 0, CAL_OK);
    CAL_PWM_SetDutyCycle_ExpectAndReturn(fake_timer, 2, 40, CAL_OK);

    bool result = PMDC_setDutyCycle(&motor, -40);

    TEST_ASSERT_TRUE(result);
    TEST_ASSERT_EQUAL_UINT8(40, motor.dutyCycle);

    /* Same operator-precedence overflow as the forward test above:
     * 40*6000=240000 overflows int16_t before /100, then *-1.
     * See the note in test_PMDC_setDutyCycle_positive_... above. */

    TEST_ASSERT_EQUAL_INT16(221, motor.currentRPM);
}

/*  PMDC_setDutyCycle -- Zero duty cycle stops the motor */

void test_PMDC_setDutyCycle_zero_stops_motor(void)
{
    CAL_GPIO_Write_ExpectAndReturn(fake_en_port, 5, RESET, CAL_OK);
    CAL_PWM_SetDutyCycle_ExpectAndReturn(fake_timer, 1, 0, CAL_OK);
    CAL_PWM_SetDutyCycle_ExpectAndReturn(fake_timer, 2, 0, CAL_OK);

    bool result = PMDC_setDutyCycle(&motor, 0);

    TEST_ASSERT_TRUE(result);
}

void test_PMDC_setDutyCycle_returns_false_for_NULL_pointer(void)
{
    bool result = PMDC_setDutyCycle(NULL, 50);
    TEST_ASSERT_FALSE(result);
}

/*  PMDC_Stop      */

void test_PMDC_Stop_disables_motor_and_zeroes_both_channels(void)
{
    CAL_GPIO_Write_ExpectAndReturn(fake_en_port, 5, RESET, CAL_OK);
    CAL_PWM_SetDutyCycle_ExpectAndReturn(fake_timer, 1, 0, CAL_OK);
    CAL_PWM_SetDutyCycle_ExpectAndReturn(fake_timer, 2, 0, CAL_OK);

    bool result = PMDC_Stop(&motor);

    TEST_ASSERT_TRUE(result);
}

/*  PMDC_Destroy */

void test_PMDC_Destroy_stops_motor_then_stops_both_PWM_channels(void)
{

   /* Destroy() first invokes Stop(), which resets the GPIO pins and 
sets the duty cycle of both channels to 0. It then calls
 CAL_PWM_Stop() for both PWM channels. */
   
    CAL_GPIO_Write_ExpectAndReturn(fake_en_port, 5, RESET, CAL_OK);
    CAL_PWM_SetDutyCycle_ExpectAndReturn(fake_timer, 1, 0, CAL_OK);
    CAL_PWM_SetDutyCycle_ExpectAndReturn(fake_timer, 2, 0, CAL_OK);
    CAL_PWM_Stop_ExpectAndReturn(fake_timer, 1, CAL_OK);
    CAL_PWM_Stop_ExpectAndReturn(fake_timer, 2, CAL_OK);

    bool result = PMDC_Destroy(&motor);

    TEST_ASSERT_TRUE(result);
}
